### PR TITLE
in-memory cache

### PR DESCRIPTION
**Pull request by ahmdrz**
Honestly , I'm not good in concurrency !
So I don't know I wrote good or bad ...
I believe you are great man in Golang and HTTP , My aim of be contributor in your project is learn from you.

Can you help me to with teaching me concurrency ?
You can teach me by tell bugs or how to write codes better than current.

> Sorry for my bad english :face_with_thermometer:

Commits are :

1. Adding ignore header for ignoring requests from cache.
2. Graceful shutdown added because if we close program , We have to save in-memory caches.
3. In-memory implemented using `map[string]Cache`

Regards.

### CODE REVIEW

**Comment by siadat** [comment]
Thanks @ahmdrz for your contribution to this project! You code looks good already!

I will have a more detailed look at it tonight. Just one thing I would like to point out now is that file-cache is kinda the main feature of this project. So, it would be a good idea to keep writing to files as before. Maybe you could simplify the logic by writing responses to files as soon as your receive them (instead of in doing them in Shutdown), then handle expiration of the in-memory cache on demand without the need of a periodical GC. :hamburger:

**Comment by ahmdrz** [comment]
Thank you @siadat
> So, it would be a good idea to keep writing to files as before...
You mean first dump to file and store in memory concurrently?
As my last commit ,
1. Store in memory
2. If expiration time reached, save to file.
3. If not exists in memory , load from file.

**Comment by ahmdrz** [comment]
Now we can save `mina` log file using `-log=<filename>`

**Comment by siadat** [comment]
I'm a bit on unsure whether Mina needs in-memory cache at all :thinking: The reason is that users might want to change the files manually to get different responses. Here are a few suggestions:

- store new requests both in file and in memory, i.e, do not delay saving to file. Basically, we want to reduce disk reads. Disk writes should stays as it was previously.
- I think ideally it would be a nice if it watched the cached files for changes. When a file changes it should invalidate the appropriate cache entry of the in-memory cache.
- If we add the file watcher, I don't think we would need expiration-times any more.

Also, I think it's best not to included unrelated changes in the same pull request. So, let's keep it as small as possible and work on log in another pull request.

Thank you for sending patches :racehorse:

**Comment by ahmdrz** [comment]
Hello again dear Mr. Siadat , Your right , This is your projects and you have to adhere on your goals.
So , I will create another PR , And I will use file watcher and work on your ideas.
First of all , I will add log file.

Regards.

**Comment by ahmdrz** [comment]
May I create another project like `mina` for myself ?

**Comment by siadat** [comment]
I sent a comment but it wasn't posted! :( I'll try to recall what I wrote.

I didn't mean to skip in-memory cache altogether, my bad! :see_no_evil: I meant an in-memory for reads would be useful, something like this:

* a request is received
* if in-memory cache already contains the request
  * use in-memory cache
* else
  * fetch response
  * write request and response to file cache
  * write request and response to in-memory cache

in another goroutine:

* watch all files in the cache dir for changes to files
* if a file is modified (e.g. a user opens it in an editor, makes changes and saves it)
  * invalidate in-memory entry for the edited file

:taco:

**Comment by siadat** [comment]
Also, I don't own this project :laughing: :speak_no_evil:

**Comment by ahmdrz** [comment]
Hi @siadat
Honestly , I wrote all of your options in my local.
I use fsnotify for watching file and all things works. But the problem is about response file.
We cannot edit it , when I changed the response file , Browser can not serve. 
The reason is file saved as data format.

**Pull request closed without merging**
